os: Visual Studio 2015

environment:
  matrix:
   - COMPILER: msys64
     MINGW_ARCH: x86_64
     MINGW_ROOT: C:\msys64\mingw64
#     CMAKE_GENERATOR: 'MSYS Makefiles'

install:
  # Use cygwin to checkout source code, due to characters in sub-repo that mingw git can't handle
  - set OLD_PATH=%PATH%
  - set PATH=%PATH%;C:\cygwin\bin
  - C:\cygwin\bin\git submodule update --init --recursive
  - set PATH=C:\msys64\usr\bin\;%OLD_PATH%
  - bash -lc "pacman --noconfirm -S make gmp gmp-devel gcc git cmake"

before_build:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && cmake -E make_directory build && cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Debug .."

build_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && cmake --build build"

test_script:
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && cmake --build build --target test"
